chore: Add code to repro bug
```
[I] ccchapman@Chriss-Mac-mini ~/S/playwright-ct-repro (main)> npm run test-ct

> playwright-ct-repro@1.0.0 test-ct
> playwright test -c playwright-ct.config.ts

Running 3 tests using 3 workers

vite v4.4.1 building for production...
✓ 9 modules transformed.
✓ built in 256ms
[vite:css] [postcss] postcss-import: /Users/ccchapman/Sites/playwright-ct-repro/src/styles/typography.css:1:1: `@layer base` is used but no matching `@tailwind base` directive is present.
CssSyntaxError: [postcss] postcss-import: /Users/ccchapman/Sites/playwright-ct-repro/src/styles/typography.css:1:1: `@layer base` is used but no matching `@tailwind base` directive is present.

    at Input.error (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/postcss/lib/input.js:106:16)
    at AtRule.error (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/postcss/lib/node.js:115:32)
    at normalizeTailwindDirectives (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/tailwindcss/lib/lib/normalizeTailwindDirectives.js:72:32)
    at /Users/ccchapman/Sites/playwright-ct-repro/node_modules/tailwindcss/lib/processTailwindFeatures.js:30:98
    at plugins (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/postcss/lib/lazy-result.js:357:16)
    at LazyResult.runAsync (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/postcss/lib/lazy-result.js:286:26)
    at compileCSS (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/vite/dist/node/chunks/dep-439026c8.js:38783:25)
    at Object.load (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/vite/dist/node/chunks/dep-439026c8.js:38735:32)
    at LazyResult.runAsync (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/postcss/lib/lazy-result.js:289:11)
    at compileCSS (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/vite/dist/node/chunks/dep-439026c8.js:38783:25)
    at Object.transform (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/vite/dist/node/chunks/dep-439026c8.js:38203:56)
    at transform (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/rollup/dist/es/shared/node-entry.js:24239:16)
    at ModuleLoader.addModuleSource (/Users/ccchapman/Sites/playwright-ct-repro/node_modules/rollup/dist/es/shared/node-entry.js:24439:30)

  3 skipped
transforming (10) node_modules/scheduler/cjs/scheduler.production.min.js
To open last HTML report run:

  npx playwright show-report
```